### ISSUE TITLE
Remove Set/Delete Capabilities

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry-holding/go-mod-core-security#14]
This module will be used for obtaining secrets from the underlying secret provider by platform microservices. These microservices are not responsible for the management of secrets, only obtaining them. Therefore there is no reason for this client module to perform write or delete operations, only "GET" operations.

**Comment by AnthonyMBonafide** [comment]
This issue has been moved to [edgexfoundry/go-mod-secrets](https://github.com/edgexfoundry/go-mod-secrets) as [issue 8](https://github.com/edgexfoundry/go-mod-secrets/issues/8).

**Comment by tsconn23** [comment]
Closing. Repo has been moved.
