### ISSUE TITLE
Add TLS Transport Support

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry-holding/go-mod-core-security#15]
There are a couple parts to this

- The configuration (presumably `SecretConfig`) needs to be extended to accommodate the path to both a token and a certificate. Both are needed to support the Vault use case.
- The HttpClient used by the SecretClient type is insufficient for making a TLS call. The Transport layer will need to be configured via TLSClientConfig. [This](https://stackoverflow.com/questions/38822764/how-to-send-a-https-request-with-a-certificate-golang) might help. 
- It sounds like the token is sent in a header so we'll need to add that to our requests.

**Comment by AnthonyMBonafide** [comment]
This issue has been moved to [edgexfoundry/go-mod-secrets](https://github.com/edgexfoundry/go-mod-secrets) as [issue 7](https://github.com/edgexfoundry/go-mod-secrets/issues/7).

**Comment by tsconn23** [comment]
Closing. Repo has been moved.
